
companyList = [
    {"name":"Т-Технологии",                       "price":2900.0,          "last":0,               "purchased": 1,    "status":""},
    {"name":"Сбербанк России",                    "price":278.77,          "last":0,               "purchased": 2,    "status":""},
    {"name":"Газпром",                            "price":126.60,          "last":0,               "purchased": 3,    "status":""},
    {"name":"ЛУКОЙЛ",                             "price":7022.5,          "last":0,               "purchased": 0,    "status":""},
    {"name":"Корпоративный центр ИКС 5",          "price":2945.0,          "last":0,               "purchased": 0,    "status":""},
    {"name":"Роснефть",                           "price":562.95,          "last":0,               "purchased": 0,    "status":""},
    {"name":"Газпром нефть",                      "price":602.80,          "last":0,               "purchased": 0,    "status":""},
    {"name":"Мечел",                              "price":104.65,          "last":0,               "purchased": 0,    "status":""},
    {"name":"РуссНефть",                          "price":124.60,          "last":0,               "purchased": 0,    "status":""},
    {"name":"НОВАТЭК",                            "price":969.0,           "last":0,               "purchased": 0,    "status":""},
    {"name":"ЯНДЕКС",                             "price":3.934,           "last":0,               "purchased": 0,    "status":""},
    {"name":"Сургутнефтегаз",                     "price":23.4,            "last":0,               "purchased": 0,    "status":""},
    {"name":"Магнит",                             "price":4882.5,          "last":0,               "purchased": 0,    "status":""},
    {"name":"Нор.Никель",                         "price":116.26,          "last":0,               "purchased": 0,    "status":""},
    {"name":"Татнефть",                           "price":653.5,           "last":0,               "purchased": 0,    "status":""},
    {"name":"Банк ВТБ",                           "price":79.28,           "last":0,               "purchased": 0,    "status":""},
    {"name":"Аэрофлот-росс.авиалин",              "price":60.99,           "last":0,               "purchased": 0,    "status":""},
    {"name":"Система",                            "price":15.036,          "last":0,               "purchased": 0,    "status":""},
    {"name":"НЛМК",                               "price":149.34,          "last":0,               "purchased": 0,    "status":""},
    {"name":"Самолет",                            "price":996.0,           "last":0,               "purchased": 0,    "status":""},
    {"name":"Полюс",                              "price":14886.0,         "last":0,               "purchased": 0,    "status":""},
    {"name":"Совкомфлот",                         "price":90.89,           "last":0,               "purchased": 0,    "status":""},
    {"name":"Московская Биржа",                   "price":197.39,          "last":0,               "purchased": 0,    "status":""},
    {"name":"Северсталь",                         "price":1292.2,          "last":0,               "purchased": 0,    "status":""},
    {"name":"ВК",                                 "price":310.4,           "last":0,               "purchased": 0,    "status":""},
    {"name":"Мобильные ТелеСистемы",              "price":212.6,           "last":0,               "purchased": 0,    "status":""},
]

